---
title: "Amsterdam Airbnb Price Prediction"
author: "Nawal Zehra Hasan"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


```{r libraries, include = FALSE, message=FALSE, warning=FALSE}
rm(list=ls())
# Import libraries
library(rmdformats)
library(kableExtra)
library(tidyverse)
library(rmdformats)
library(stringr) 
library(rstatix)
library(scales)
library(Metrics)
library(caret)
library(ggpubr)
library(cowplot)
library(dplyr)
library(skimr)
library(modelsummary)
library(grid)
#install.packages("glmnet")
library(glmnet)
library(Hmisc)
library(ranger)
library(RColorBrewer)
library(pdp)
# install.packages("gbm")
library(gbm)
# install.packages("rattle")
library(rattle)
# colours for charts
colours <- c(brewer.pal( 3, "Set2" )[1], brewer.pal( 3, "Set2" )[2], brewer.pal( 3, "Set2" )[3])
```

```{r Import data, message=FALSE, warning=FALSE, include=FALSE, cache=TRUE}
# Import data
data <- read_csv("https://raw.githubusercontent.com/nawalhasan/DA3/main/Assignment2/data/amsterdam_raw.csv")
```

```{r, include = FALSE, message=FALSE, warning=FALSE}
# --------------------------- FIRST LOOK INTO DATA ------------------------ #
glimpse(data)
skim(data)

# Filtering for apartments which accommodate 2-6 persons
data <- data %>%  filter(between(accommodates, 2, 6))

# summary statistics for the data
data %>%
  group_by(accommodates) %>%
  dplyr::summarize(mean_price = mean(price, na.rm=TRUE))
Hmisc::describe(data$price)

# Check to see if there are any duplicates
duplicated(names(data))

# Drop unused columns
data <- data[grep("^host", colnames(data), invert = TRUE)]
data <- data %>% dplyr::select(-contains("maximum"))
data <- data[grep("^calculated", colnames(data), invert = TRUE)]
data <- data %>% select(-c("listing_url","scrape_id","last_scraped","name","description","neighborhood_overview","picture_url", "neighbourhood_group_cleansed","bathrooms","minimum_minimum_nights","minimum_nights_avg_ntm","calendar_updated","calendar_last_scraped","number_of_reviews_ltm","number_of_reviews_l30d","license","reviews_per_month","availability_30","availability_60","availability_90","availability_365","neighbourhood","has_availability", "first_review", "last_review"))

## Create Numerical variables
data <- data %>%
  mutate(
    price_day = as.numeric(gsub("[^0-9.]", "", price)))

```


```{r, include = FALSE, message=FALSE, warning=FALSE }
# --------------------------- DEAL WITH MISSING VALUES ------------------------ #

# A) drop if no target value
data <- data %>%
  drop_na(price)

# B) Impute if few
data <- data %>%
  mutate(
    beds = ifelse(is.na(beds), accommodates, beds), #assume beds=accomodates
    minimum_nights=ifelse(is.na(minimum_nights),1, minimum_nights),
    number_of_reviews=ifelse(is.na(number_of_reviews),1, number_of_reviews),
    beds=ifelse(is.na(beds),0, beds),
  )

# C) drop columns when many missing: review_scores_value & review_scores_communication
to_drop <- c("review_scores_value", "review_scores_communication")
data <- data %>%
  select(-one_of(to_drop))

to_filter <- sapply(data, function(x) sum(is.na(x)))
to_filter[to_filter > 0]

# D)  Replace missing variables re-reviews with zero, when no review + add flags
data <- data %>%
  mutate(
    flag_review_scores_rating = ifelse(is.na(review_scores_rating),1, 0),
    review_scores_rating    = ifelse(is.na(review_scores_rating),median(review_scores_rating, na.rm = T), review_scores_rating))

# check one flagged variable
datasummary( factor(flag_review_scores_rating) ~ N , data) 

```


```{r, include = FALSE, message=FALSE, warning=FALSE}
# --------------------------- FILTER PROPERTY TYPES ------------------------ #
# Keep if property type is Entire loft, Entire serviced apartment
data <- data %>% 
  filter( property_type %in% c('Entire serviced apartment', 'Entire loft',  'Entire rental unit') )

# rename property_type categories to make them shorter
data <- data %>% mutate( property_type = 
                         ifelse( property_type == 'Entire serviced apartment', 'serviced_apartment',
                         ifelse( property_type == 'Entire loft', 'loft',
                         ifelse( property_type == 'Entire rental unit', 'rental unit',"."))))

# convert property_type to factor
data <- data %>%
  mutate(f_property_type = factor(property_type))

# convert neighborhood_cleansed to factor
data <- data %>% 
  mutate( f_neighbourhood = factor(neighbourhood_cleansed))

```

```{r, include = FALSE, message=FALSE, warning=FALSE}
# --------------------------- EXTRACT NUMBER OF BATHROOMS ------------------------ #

data <- data  %>% 
  mutate(bathrooms = as.numeric(gsub("[a-zA-Z ]", "", data$bathrooms_text)))
data$bathrooms_text <- NULL

# add new numeric columns from certain columns
numericals <- c("accommodates", "bathrooms" , "minimum_nights","beds" ,"review_scores_rating","number_of_reviews", "bedrooms")

data <- data %>%
  mutate_at(vars(numericals), funs("n"=as.numeric))

# rename columns so they start with n_ as opposed to end with _n
nnames <- data %>%
  select(ends_with("_n")) %>%
  names()
nnames_i <- match(nnames, colnames(data))
colnames(data)[nnames_i] <- paste0("n_", numericals)
```

```{r,include = FALSE, message=FALSE, warning=FALSE}
# --------------------------- EXTRACT AMENITIES ------------------------ #

# remove unnecessary signs and convert to list
data$amenities <- tolower( data$amenities )
data$amenities <- gsub("\\[","", data$amenities)
data$amenities <- gsub("\\]","", data$amenities)
data$amenities <- gsub('\\"',"",data$amenities)
data$amenities <- as.list(strsplit(data$amenities, ","))

# define levels and dummies and append to df
levs <- levels(factor(unlist(data$amenities)))
data <- cbind(data,as.data.frame(do.call(rbind, lapply(lapply(data$amenities, factor, levs), table))))

# function to aggregate several columns of same type/category into one generic binary column
aggregate_columns <- function(word){
  
  # subset columns which contain a specific word and save them to another dataframe, also select 'id' to use for merge later
  new_df <- data %>% select(contains(word),"id")
  
  # go row by row to see if any of the rows have a 1, if it does, populate new column 'col_name' with 1
  new_df$col_name <- apply(new_df[0:ncol(new_df)], 1, function(x) ifelse(any(x == 1), '1', '0'))
  
  # save new column and id column to another dataframe, this new dataframe is used to merge with original dataframe
  new_df_merge <- new_df %>% select(id,col_name)
  
  # merge original dataframe and new_df_merge by 'id'
  data <- merge(data,new_df_merge,by = "id", all = FALSE)
  
  # remove the new column and 'id' column from the new_df dataframe
  new_df <- new_df %>% select(-c(id,col_name))

  # remove the selected columns from original dataframe since they have already been aggregated into a new column and merged
  data <<- data %>% select(-colnames(new_df))
}

# aggregate columns for a few amenities that could be important for predicting price
aggregate_columns("wifi")
data <- data %>% rename("wifi" = col_name)

aggregate_columns("refrigerator")
data <- data %>% rename("refrigerator" = col_name)

aggregate_columns("air conditioning")
data <- data %>% rename("air_conditioning" = col_name)

aggregate_columns("baby")
data <- data %>% rename("baby" = col_name)

aggregate_columns("beach")
data <- data %>% rename("beach" = col_name)

aggregate_columns("stove")
data <- data %>% rename("stove" = col_name)

aggregate_columns("free parking")
data <- data %>% rename("free_parking" = col_name)

aggregate_columns("office")
data <- data %>% rename("office" = col_name)

aggregate_columns("coffee maker")
data <- data %>% rename("coffee_maker" = col_name)

aggregate_columns("garden")
data <- data %>% rename("garden" = col_name)

aggregate_columns("gym")
data <- data %>% rename("gym" = col_name)

# drop the amenities column because a csv cannot store it since it is a list
data <- data %>% select( -amenities )

# drop amenities that were not used
data <- data[ -c(31:398)]

```

```{r, include = FALSE, message=FALSE, warning=FALSE}
# --------------------------- CREATE DUMMY VARIABLES ------------------------ #

data$instant_bookable <- replace(data$instant_bookable,data$instant_bookable == 'TRUE', "1")
data$instant_bookable <- replace(data$instant_bookable,data$instant_bookable == 'FALSE', "0")

# rename dummies
dummies <- c( "instant_bookable", "wifi", "refrigerator", "air_conditioning", "baby", "beach", "stove", "free_parking", "office", "coffee_maker", "garden", "gym")
data <- data %>%
  mutate_at(vars(dummies), funs("d"= (.)))
# rename columns
dnames <- data %>%
  select(ends_with("_d")) %>%
  names()
dnames_i <- match(dnames, colnames(data))
colnames(data)[dnames_i] <- paste0("d_", tolower(gsub("[^[:alnum:]_]", "",dummies)))

# check if price is missing
nrow(data %>% filter( is.na(price_day)))
```


```{r, include = FALSE, message=FALSE, warning=FALSE}
# keep columns if contain d_, n_,f_, p_, usd_ and some others
data <- data %>%
  select(id,price_day,matches("^d_.*|^n_.*|^f_.*"))
amenities_convert<- data %>%
  select(starts_with("d_"),"id") 
amenities_convert <- amenities_convert %>%mutate_if(is.integer,as.numeric)
glimpse(amenities_convert)
data <- data %>%
  select(-starts_with("d_")) 
data <- merge(data,amenities_convert, by = "id")
data <- data %>% mutate(id = as.numeric(id))
```

```{r, include = FALSE, warning = FALSE, message = FALSE}
# Change Infinite values with NaNs
for (j in 1:ncol(data) ) data.table::set(data, which(is.infinite(data[[j]])), j, NA)

# change characters to factors
data <- data %>%
  mutate_if(is.character, factor)
```

```{r, include = FALSE, warning = FALSE, message = FALSE}
write_csv(data,"amsterdam_clean.csv")
```
